# Generated by Django 3.1.2 on 2020-10-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangemen_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emmpname', models.CharField(blank=True, max_length=250, null=True)),
                ('sMonth', models.IntegerField()),
                ('sYear', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=3, max_digits=9)),
                ('total_salary', models.DecimalField(decimal_places=3, max_digits=9)),
                ('total_Diesc', models.DecimalField(decimal_places=3, max_digits=9)),
                ('net_salary', models.DecimalField(decimal_places=3, max_digits=9)),
                ('overtime', models.DecimalField(decimal_places=3, max_digits=9)),
                ('health_care', models.DecimalField(decimal_places=3, max_digits=9)),
                ('solfa1', models.DecimalField(decimal_places=3, max_digits=9)),
                ('solfa2', models.DecimalField(decimal_places=3, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.DecimalField(decimal_places=3, max_digits=9)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=9)),
                ('disc_amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=250)),
                ('mangment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.mangement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
