# Generated by Django 3.1.2 on 2020-10-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='moblie_no',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='send_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='send_voice',
            field=models.BooleanField(default=True),
        ),
    ]
