# Generated by Django 3.1.2 on 2020-10-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201025_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmportEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.IntegerField()),
                ('EmpName', models.CharField(max_length=150)),
                ('MangementId', models.IntegerField()),
            ],
        ),
    ]
