# Generated by Django 3.1.2 on 2020-10-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_emportemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mangment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.mangement'),
        ),
    ]
