# Generated by Django 3.1.2 on 2020-10-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201029_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='moblie_no',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
